model = "gpt-5.3-codex"
model_reasoning_effort = "xhigh"
personality = "pragmatic"
suppress_unstable_features_warning = true


[sandbox_workspace_write]
network_access = true


# Add your trusted project paths here:
# [projects."/path/to/project"]
# trust_level = "trusted"

[features]
ghost_commit = false
unified_exec = true
apply_patch_freeform = true
skills = true
shell_snapshot = true

[projects."/Users/petar/Code/amplify-cli"]
trust_level = "trusted"

[projects."/Users/petar/Code/amplify-web"]
trust_level = "trusted"

[projects."/Users/petar"]
trust_level = "trusted"

[projects."/Users/petar/Downloads"]
trust_level = "trusted"

[projects."/Users/petar/Code/finde-ts"]
trust_level = "trusted"

[projects."/Users/petar/Code/bytebottom/finde"]
trust_level = "trusted"

[projects."/Users/petar/Code/workera"]
trust_level = "trusted"

[projects."/Users/petar/Code/skills"]
trust_level = "untrusted"

[projects."/Users/petar/Code/amplify"]
trust_level = "trusted"

[projects."/Users/petar/.claude/skills/analytics"]
trust_level = "trusted"

[projects."/Users/petar/Code/examples/lennys-podcast-transcripts"]
trust_level = "trusted"
